version: '2'

volumes:
  audio_cache:

services:
  backend:
    build: src
    image: thatmusic_backend
    restart: always
    env_file:
      - .env
    volumes:
      - audio_cache:/cache
    ports:
      - 127.0.0.1:${CONTAINER_PORT}:8000
